---
vpcs:
  vpc-tf-testaccount-2:
    cidr: "10.2.0.0/16"
    azs:
      - eu-west-2a
      - eu-west-2b
      - eu-west-2c
    private_subnets:
      - 10.2.1.0/24
      - 10.2.2.0/24
      - 10.2.3.0/24
  vpc-tf-testaccount-3:
    cidr: "10.3.0.0/16"
    azs:
      - eu-west-2a
      - eu-west-2b
      - eu-west-2c
    private_subnets:
      - 10.3.1.0/24
      - 10.3.2.0/24
      - 10.3.3.0/24
