---
# site level config
global_var: "overridden in deployments/app"
tier_var: "set in deployments/app/"
env_var: "set in deployments/app/prod"
vm_dns_list: ["10.13.36.12", "10.13.36.13"]
vm_gateway: "10.13.36.1"
vm_datacentre: "Olivers Yard"
# vm_datastore_cluster: "OY_PS_DSC_Prod"
vm_datastore: "Vol-dc1clu01-Prod-03"
vm_cluster: "dc1clu01"
