---

iam_users:
  jbloggs:
    force_destroy: false
    pgp_key: "keybase:fsemti808"
    password_reset_required: false
    permissions_boundary: ""
  jdoe:
    force_destroy: false
    pgp_key: "keybase:fsemti808"
    password_reset_required: false
    permissions_boundary: ""
