---
ct_management_account_id: "288826279134"
log_archive_account_id: "870598241413"
audit_account_id: "862694514466"
aft_management_account_id: "303945814851"
tf_backend_secondary_region: "eu-west-1"
github_username: "sportingsolutions"
ct_home_region: "eu-west-2"


